version: '3.7'
services:
  proxy:
    build: M1_proxy
    ports:
      - "8080:80"
    networks:
      internal_nw:
        ipv4_address: 172.28.0.2
  main:
    build: M2_server
    networks:
      internal_nw:
        ipv4_address: 172.28.0.3
networks:
  internal_nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16