# CARS

###
POST http://localhost:8080/api/cars
Content-Type: application/json

{
"vin": "testowy1",
"color": "niebieski",
  "model": "e46"
}
###
POST http://localhost:8080/api/cars
Content-Type: application/json

{
  "vin": "testowy2",
  "color": "czerwony",
  "model": "e36"
}
###
POST http://localhost:8080/api/cars
Content-Type: application/json

{
  "vin": "testowy3",
  "color": "czarny",
  "model": "e46"
}
###
GET http://localhost:8080/api/cars/1
###
GET http://localhost:8080/api/cars/
###
GET http://localhost:8080/api/cars/1/model
###
DELETE http://localhost:8080/api/cars/1
###
DELETE http://localhost:8080/api/cars/testowy1
###
PUT http://localhost:8080/api/cars/1
Content-Type: application/json

{
  "color": "red"
}
###

# MODELS #

###
POST http://localhost:8080/api/models
Content-Type: application/json

{
  "name": "e46",
  "hp": 231
}
###
POST http://localhost:8080/api/models
Content-Type: application/json

{
  "name": "e36",
  "hp": 197
}
###
GET http://localhost:8080/api/models
###
GET http://localhost:8080/api/models/e46
###
GET http://localhost:8080/api/models/e46/cars
###
PUT http://localhost:8080/api/models/e46
Content-Type: application/json

{
  "hp": 210
}
###
DELETE http://localhost:8080/api/models/e46
